plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - [Blog_post_1](https://vanman247.github.io/Senior-Project/Blog_post_1.html){:target="_blank" rel="noopener"}
  - [Blog_post_2](https://vanman247.github.io/Senior-Project/Blog_post_2.html){:target="_blank" rel="noopener"}
  - [Blog_post_3](https://vanman247.github.io/Senior-Project/Blog_post_3.html){:target="_blank" rel="noopener"}
  - [Blog_post_4](https://vanman247.github.io/Senior-Project/Blog_post_4.html){:target="_blank" rel="noopener"}
